version: "3"
services:
  redis:
    image: redis:4
    hostname: redis-host
    container_name: redis-host
    ports:
      - "6379:6379"
    networks:
      - internal-network
  cassandra:
    image: cassandra:3.11
    hostname: cassandra-host
    container_name: cassandra-host
    ports:
      - "9042:9042"
    networks:
      - internal-network
networks:
  internal-network:
